version: '3.3'
services:

  cyber-ui:
    image: cybernode/cui-browser:latest
    restart: unless-stopped
    ports:
      - 32500:80
    environment:
       CYBER_CHAINGEAR_API: http://93.125.26.210:32600
       CYBER_SEARCH_API: http://93.125.26.210:32901
       CYBER_MARKETS_API: http://93.125.26.210:32800
       CYBER_MARKETS_STREAM_API: ws://93.125.26.210:32801

networks:
    default:
        external:
            name: staging_default