version: 2

  # This config file uses YAML aliases
  # http://blog.daemonl.com/2016/02/yaml.html
  # https://github.com/cyklo/Bukkit-OtherBlocks/wiki/Aliases-(advanced-YAML-usage)
aliases:

  # Common configuration for all jobs
  - &defaults
    working_directory: ~/build
    docker:
      - image: circleci/openjdk:8-jdk

jobs:

  update_changelog:
    <<: *defaults
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - checkout
      - run:
          name: Build And Update Changelog
          command: |
            cid=$(docker run -d -it ferrarimarco/github-changelog-generator -u cybercongress -p cybernode --exclude-tags-regex .*[.].*[.].*[.].* --token $CHANGELOG_GITHUB_TOKEN )
            docker attach $cid
            docker cp $cid:/usr/local/src/your-app/CHANGELOG.md ./CHANGELOG.md
            diff=$(git diff CHANGELOG.md)
            if [[  -n  "$diff" ]]; then
              git config --global user.email "cybercongress42@gmail.com"
              git config --global user.name "Cyber Admin"
              git add CHANGELOG.md
              git commit -m "Circle CI: Update Changelog"
              git push --set-upstream origin master
            fi


  update_docs:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Clone congress repo
          working_directory: ~/workdir
          command: |
            git clone -q --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/congress.git
      - deploy:
          name: Update docs from cybernode repo
          working_directory: ~/workdir/congress
          command: |
            # We need to remove current files in folder to avoid duplicating renamed files
            rm -rf ./knowledge/docs/cybernode/*
            cp -r ~/build/docs/. ./knowledge/docs/cybernode/
            git add -N knowledge/docs/cybernode
            diff=$(git diff knowledge/docs/cybernode/)
            if [[  -n  "$diff" ]]; then
              git config user.email "cybercongress42@gmail.com"
              git config user.name "Cyber Admin"
              git add knowledge/docs/cybernode/
              git commit -m "Circle CI: Update Docs"
              # Push quietly to prevent showing the token in log
              git push -q https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/congress.git master
            fi

workflows:
  version: 2

  cybernode_build:
    jobs:
      - update_changelog:
          filters:
            branches:
              only: master
      - update_docs:
          filters:
            branches:
              only: master